import React, { useCallback, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  FileText,
  X,
  Volume2,
  VolumeX,
  FileUp,
  Download,
  Languages,
  History,
  MessageSquare,
  Send,
  Mic,
  MicOff,
  GraduationCap,
  BookOpen,
  Loader2,
  Trash2,
} from 'lucide-react';
import { UserProfile } from '../types';
import { generateAdaptiveResponse } from '../services/gemini';
import { speak, cancelSpeech, unlockSpeechSynthesis } from '../lib/tts';
import { toast } from './Toast';
import { cleanVisionDescription } from '../lib/visionCleaner';

export interface SavedDocItem {
  id: string;
  title: string;
  sourceType: 'pdf' | 'image' | 'audio' | 'speech';
  summary: string;
  fullText?: string;
  targetLang: 'ar' | 'en' | 'fr';
  createdAt: string;
}

export interface DocChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

export const DOC_HISTORY_KEY = 'cognify_vision_doc_history';

export function exportToWordDocument(title: string, summary: string, fullText?: string, lang: 'ar' | 'en' | 'fr' = 'ar') {
  if (typeof window === 'undefined') return;
  const isAr = lang === 'ar';
  const cleanSummary = (summary || '').replace(/\*\*/g, '').replace(/###/g, '');
  const cleanFull = (fullText || '').replace(/\*\*/g, '').replace(/###/g, '');

  const html = `
    <!DOCTYPE html>
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset='utf-8'>
      <title>${title}</title>
      <!--[if gte mso 9]>
      <xml>
        <w:WordDocument>
          <w:View>Print</w:View>
          <w:Zoom>100</w:Zoom>
          <w:DoNotOptimizeForBrowser/>
        </w:WordDocument>
      </xml>
      <![endif]-->
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, Arial, sans-serif;
          direction: ${isAr ? 'rtl' : 'ltr'};
          text-align: ${isAr ? 'right' : 'left'};
          line-height: 1.8;
          color: #1e293b;
          margin: 40px;
        }
        .header {
          border-bottom: 3px solid #4f46e5;
          padding-bottom: 12px;
          margin-bottom: 24px;
        }
        h1 {
          font-size: 22pt;
          color: #1e1b4b;
          margin-bottom: 6px;
        }
        .meta {
          font-size: 11pt;
          color: #64748b;
        }
        .section-title {
          font-size: 16pt;
          font-weight: bold;
          color: #4338ca;
          margin-top: 24px;
          margin-bottom: 10px;
          border-left: ${isAr ? 'none' : '4px solid #4338ca'};
          border-right: ${isAr ? '4px solid #4338ca' : 'none'};
          padding-${isAr ? 'right' : 'left'}: 10px;
        }
        .summary-box {
          background-color: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 16px;
          font-size: 13pt;
          color: #0f172a;
        }
        .full-text-box {
          font-size: 12pt;
          color: #334155;
          white-space: pre-wrap;
        }
        .footer {
          margin-top: 40px;
          border-top: 1px solid #e2e8f0;
          padding-top: 12px;
          font-size: 10pt;
          color: #94a3b8;
          text-align: center;
        }
      </style>
    </head>
    <body dir="${isAr ? 'rtl' : 'ltr'}">
      <div class="header">
        <h1>${title || (isAr ? 'ملخص ومستند كوجنيفي' : 'Cognify Document')}</h1>
        <div class="meta">
          ${isAr ? 'تم الاستخراج والتلخيص عبر منصة كوجنيفي للذكاء الاصطناعي والرفيق البصري' : 'Generated by Cognify AI Visual Companion'} • ${new Date().toLocaleDateString(isAr ? 'ar-EG' : 'en-US')}
        </div>
      </div>
      
      <div class="section-title">
        ${isAr ? '📌 الزبدة وخلاصة المحاضرة / المستند' : '📌 Core Takeaways & Summary'}
      </div>
      <div class="summary-box">
        ${cleanSummary.replace(/\n/g, '<br/>')}
      </div>

      ${cleanFull ? `
        <div class="section-title">
          ${isAr ? '📝 تفاصيل النص المستخرج كاملاً' : '📝 Full Extracted Content'}
        </div>
        <div class="full-text-box">
          ${cleanFull.replace(/\n/g, '<br/>')}
        </div>
      ` : ''}

      <div class="footer">
        Cognify 2.0 • Empowering Inclusive Learning and Accessibility
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff' + html], { type: 'application/msword;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeTitle = (title || 'cognify-document').replace(/[^\w\u0600-\u06FF\s-]/g, '').trim().replace(/\s+/g, '_');
  a.download = `${safeTitle || 'cognify-document'}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

interface DocumentStudioModalProps {
  isOpen: boolean;
  onClose: () => void;
  profile: UserProfile;
  companionLang: 'ar' | 'en' | 'fr';
  onAnnounce?: (msg: string) => void;
}

export default function DocumentStudioModal({
  isOpen,
  onClose,
  profile,
  companionLang,
  onAnnounce,
}: DocumentStudioModalProps) {
  const [docStudioTab, setDocStudioTab] = useState<'pdf' | 'audio-rec' | 'speech-to-text' | 'history'>('pdf');
  const [docLoading, setDocLoading] = useState(false);
  const [docStatusText, setDocStatusText] = useState('');

  const [currentDoc, setCurrentDoc] = useState<SavedDocItem & { fileBase64?: string; fileMime?: string } | null>(null);
  const [docTargetLang, setDocTargetLang] = useState<'ar' | 'en' | 'fr'>(() => companionLang || 'ar');
  const [docViewMode, setDocViewMode] = useState<'summary' | 'full'>('summary');

  const [docChatMessages, setDocChatMessages] = useState<DocChatMessage[]>([]);
  const [docChatInput, setDocChatInput] = useState('');
  const [isDocChatAnswering, setIsDocChatAnswering] = useState(false);

  const [isRecordingAudio, setIsRecordingAudio] = useState(false);
  const [audioRecordDuration, setAudioRecordDuration] = useState(0);
  const [liveSpeechTranscript, setLiveSpeechTranscript] = useState('');
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);
  const recordTimerRef = useRef<any>(null);
  const speechRecRef = useRef<any>(null);

  const [isSpeakingDoc, setIsSpeakingDoc] = useState(false);
  const [isDictating, setIsDictating] = useState(false);
  const [dictationText, setDictationText] = useState('');
  const [textToReadAloud, setTextToReadAloud] = useState('');

  const [docHistory, setDocHistory] = useState<SavedDocItem[]>(() => {
    if (typeof window !== 'undefined') {
      try {
        const raw = window.localStorage.getItem(DOC_HISTORY_KEY);
        return raw ? JSON.parse(raw) : [];
      } catch {
        return [];
      }
    }
    return [];
  });

  const saveDocToHistory = useCallback((item: SavedDocItem) => {
    setDocHistory((prev) => {
      const filtered = prev.filter((d) => d.id !== item.id);
      const updated = [item, ...filtered].slice(0, 30);
      if (typeof window !== 'undefined') {
        window.localStorage.setItem(DOC_HISTORY_KEY, JSON.stringify(updated));
      }
      return updated;
    });
  }, []);

  const deleteDocFromHistory = useCallback((id: string) => {
    setDocHistory((prev) => {
      const updated = prev.filter((d) => d.id !== id);
      if (typeof window !== 'undefined') {
        window.localStorage.setItem(DOC_HISTORY_KEY, JSON.stringify(updated));
      }
      return updated;
    });
  }, []);

  const processDocumentFile = async (file: File) => {
    if (!file) return;
    setDocLoading(true);
    const targetLanguage = docTargetLang;
    const isAr = targetLanguage === 'ar';
    const isFr = targetLanguage === 'fr';

    const statusMsg = isAr
      ? `جاري فحص وقراءة "${file.name}" وترجمة وتلخيص المحاضرة...`
      : isFr
      ? `Analyse de "${file.name}", traduction et synthèse en cours...`
      : `Analyzing "${file.name}", translating and summarizing lecture...`;
    setDocStatusText(statusMsg);
    onAnnounce?.(statusMsg);
    speak(statusMsg, isAr ? 'Arabic' : isFr ? 'French' : 'English');

    try {
      const reader = new FileReader();
      const fileDataPromise = new Promise<{ base64: string; mimeType: string }>((resolve, reject) => {
        reader.onload = () => {
          const res = reader.result as string;
          const match = res.match(/^data:([^;]+);base64,(.+)$/);
          if (match) {
            resolve({ mimeType: match[1], base64: match[2] });
          } else {
            resolve({ mimeType: file.type || 'application/pdf', base64: res });
          }
        };
        reader.onerror = (e) => reject(e);
        reader.readAsDataURL(file);
      });

      const { base64, mimeType } = await fileDataPromise;

      const prompt = `أنت معلم وأكاديمي متميز ومترجم ذكي وخبير تلخيص للمكفوفين وضعاف البصر.
المستند المرفق هو محاضرة أو كتاب أو ورقة دراسية بعنوان "${file.name}".
المطلوب منك بدقة فائقة:
1. اقرأ واستخرج محتوى هذا المستند كاملاً.
2. إذا كان المستند بأي لغة أخرى (مثل الإنجليزية)، ترجمه وفصّله بدقة إلى لغة الهدف المطلوبة: "${isAr ? 'اللغة العربية العامية المصرية الواضحة والمفهومة للطلاب' : isFr ? 'Français' : 'English'}".
3. قدّم الإجابة في قسمين محددين:
---SUMMARY_START---
اكتب هنا "المفيد والزبدة الصافية للمحاضرة": ملخص شديد الوضوح والتركيز يبرز الفكرة الجوهرية، القوانين أو النظريات الأساسية، القرارات أو التواريخ أو الأرقام الحاسمة، بدون أي حشو.
---SUMMARY_END---

---FULLTEXT_START---
اكتب هنا النص المقروء والمستخرج من المستند مترجماً ومفصلاً بالكامل كلمة بكلمة أو فقرة بفقرة.
---FULLTEXT_END---`;

      const aiResponse = await generateAdaptiveResponse(
        prompt,
        {
          ...profile,
          language: isAr ? 'Egyptian Ammiya' : isFr ? 'French' : 'English',
        },
        [],
        [{ name: file.name, type: mimeType, data: base64 }]
      );

      let summary = '';
      let fullText = '';

      if (aiResponse.includes('---SUMMARY_START---') && aiResponse.includes('---SUMMARY_END---')) {
        summary = aiResponse.split('---SUMMARY_START---')[1].split('---SUMMARY_END---')[0].trim();
      }
      if (aiResponse.includes('---FULLTEXT_START---') && aiResponse.includes('---FULLTEXT_END---')) {
        fullText = aiResponse.split('---FULLTEXT_START---')[1].split('---FULLTEXT_END---')[0].trim();
      }

      if (!summary && !fullText) {
        summary = aiResponse;
      }

      const cleanSummary = cleanVisionDescription(summary, targetLanguage);
      const cleanFull = cleanVisionDescription(fullText, targetLanguage);

      const docItem: SavedDocItem = {
        id: `doc_${Date.now()}`,
        title: file.name.replace(/\.[^/.]+$/, ''),
        sourceType: file.type.includes('pdf') ? 'pdf' : 'image',
        summary: cleanSummary || summary,
        fullText: cleanFull || fullText,
        targetLang: targetLanguage,
        createdAt: new Date().toISOString(),
      };

      setCurrentDoc({
        ...docItem,
        fileBase64: base64,
        fileMime: mimeType,
      });
      saveDocToHistory(docItem);
      setDocChatMessages([
        {
          role: 'assistant',
          content: isAr
            ? `أهلاً بك! لقد استخرجت ولخصت ملف "${docItem.title}". يمكنك الآن سؤالي أي استفسار أو شرح لأي نقطة غير واضحة!`
            : `I've analyzed and summarized "${docItem.title}". Feel free to ask me any question or ask for explanations!`,
        },
      ]);

      setDocLoading(false);
      setDocStatusText('');

      const readout = isAr
        ? `تم تلخيص ملف ${docItem.title} بنجاح. إليك أهم ما في المحاضرة: ${cleanSummary || summary}`
        : `Summary of ${docItem.title} is ready: ${cleanSummary || summary}`;

      onAnnounce?.(readout);
      speak(readout, isAr ? 'Arabic' : isFr ? 'French' : 'English', {
        onStart: () => setIsSpeakingDoc(true),
        onEnd: () => setIsSpeakingDoc(false),
        onError: () => setIsSpeakingDoc(false),
      });
    } catch (err: any) {
      console.error('Failed to process document:', err);
      setDocLoading(false);
      setDocStatusText('');
      const errMsg = isAr
        ? 'عذراً، حدث خطأ أثناء قراءة المستند. تأكد من حجم الملف واتصالك بالإنترنت.'
        : 'Failed to process document. Please check the file and try again.';
      toast.error(errMsg);
      speak(errMsg, isAr ? 'Arabic' : isFr ? 'French' : 'English');
    }
  };

  const startAudioLectureRecording = async () => {
    try {
      unlockSpeechSynthesis();
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      audioChunksRef.current = [];
      const mediaRecorder = new MediaRecorder(stream);
      mediaRecorderRef.current = mediaRecorder;

      mediaRecorder.ondataavailable = (e) => {
        if (e.data.size > 0) audioChunksRef.current.push(e.data);
      };

      mediaRecorder.start(250);
      setIsRecordingAudio(true);
      setAudioRecordDuration(0);
      setLiveSpeechTranscript('');

      if (recordTimerRef.current) clearInterval(recordTimerRef.current);
      recordTimerRef.current = setInterval(() => {
        setAudioRecordDuration((prev) => prev + 1);
      }, 1000);

      const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
      if (SpeechRecognition) {
        try {
          const rec = new SpeechRecognition();
          rec.continuous = true;
          rec.interimResults = true;
          rec.lang = docTargetLang === 'ar' ? 'ar-EG' : docTargetLang === 'fr' ? 'fr-FR' : 'en-US';
          rec.onresult = (event: any) => {
            let transcript = '';
            for (let i = 0; i < event.results.length; i++) {
              transcript += event.results[i][0].transcript + ' ';
            }
            setLiveSpeechTranscript(transcript.trim());
          };
          rec.start();
          speechRecRef.current = rec;
        } catch {
          /* ignore speech rec fallback */
        }
      }

      const startMsg = companionLang === 'ar' ? 'بدأ تسجيل المحاضرة الصوتية الآن...' : 'Lecture recording started...';
      toast.info(startMsg);
    } catch (err) {
      console.error('Error starting audio recording:', err);
      toast.error(companionLang === 'ar' ? 'تعذر الوصول للميكروفون.' : 'Microphone access denied.');
    }
  };

  const stopAudioLectureRecording = async () => {
    if (!mediaRecorderRef.current || !isRecordingAudio) return;

    if (recordTimerRef.current) {
      clearInterval(recordTimerRef.current);
      recordTimerRef.current = null;
    }

    if (speechRecRef.current) {
      try {
        speechRecRef.current.stop();
      } catch {
        /* ignore */
      }
      speechRecRef.current = null;
    }

    setIsRecordingAudio(false);
    setDocLoading(true);

    const isAr = docTargetLang === 'ar';
    const isFr = docTargetLang === 'fr';
    const statusMsg = isAr
      ? 'جاري تفريغ الصوت المسجل وتلخيص المحاضرة واستخراج النقاط الجوهرية...'
      : 'Transcribing recorded lecture and generating key takeaways...';
    setDocStatusText(statusMsg);
    onAnnounce?.(statusMsg);
    speak(statusMsg, isAr ? 'Arabic' : isFr ? 'French' : 'English');

    const recordedTranscript = liveSpeechTranscript;

    mediaRecorderRef.current.onstop = async () => {
      try {
        mediaRecorderRef.current?.stream?.getTracks().forEach((t) => t.stop());

        const lectureTitle = isAr
          ? `محاضرة صوتية مسجلة ${new Date().toLocaleDateString('ar-EG')}`
          : `Recorded Audio Lecture ${new Date().toLocaleDateString('en-US')}`;

        let prompt = '';
        let attachments: any[] = [];

        if (recordedTranscript && recordedTranscript.length > 20) {
          prompt = `أنت معلم وأكاديمي خبير ومساعد للمكفوفين.
إليك تفريغ صوتي لمحاضرة مسجلة مباشرة:
"${recordedTranscript}"

المطلوب:
1. لخّص المحاضرة في "المفيد والزبدة الصافية" (الفكرة الجوهرية، المفاهيم الأساسية، التكليفات).
2. استخرج النقاط المهمة والتعريفات بصيغة واضحة وبلغة ${isAr ? 'عربية عامية راقية ومفهومة' : isFr ? 'française' : 'English'}.
3. نسق النص ليكون صالحاً للقراءة بالصوت والتصدير لملف Word.
قدم الإجابة في:
---SUMMARY_START---
[الملخص والزبدة الصافية]
---SUMMARY_END---
---FULLTEXT_START---
${recordedTranscript}
---FULLTEXT_END---`;
        } else {
          const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
          const reader = new FileReader();
          const audioBase64 = await new Promise<string>((resolve) => {
            reader.onload = () => {
              const res = reader.result as string;
              resolve(res.replace(/^data:[^;]+;base64,/, ''));
            };
            reader.readAsDataURL(audioBlob);
          });

          attachments.push({
            name: 'lecture.webm',
            type: 'audio/webm',
            data: audioBase64,
          });

          prompt = `استمع إلى هذا التسجيل الصوتي للمحاضرة بدقة وافرغه ولخصه في الزبدة والمفيد باللغة ${isAr ? 'العربية' : isFr ? 'الفرنسية' : 'الإنجليزية'}.
قدم الإجابة بالأقسام:
---SUMMARY_START---
[خلاصة المحاضرة وأهم النقاط]
---SUMMARY_END---
---FULLTEXT_START---
[تفريغ المحاضرة المسجلة كاملاً]
---FULLTEXT_END---`;
        }

        const aiResponse = await generateAdaptiveResponse(
          prompt,
          { ...profile, language: isAr ? 'Egyptian Ammiya' : isFr ? 'French' : 'English' },
          [],
          attachments
        );

        let summary = '';
        let fullText = '';
        if (aiResponse.includes('---SUMMARY_START---') && aiResponse.includes('---SUMMARY_END---')) {
          summary = aiResponse.split('---SUMMARY_START---')[1].split('---SUMMARY_END---')[0].trim();
        }
        if (aiResponse.includes('---FULLTEXT_START---') && aiResponse.includes('---FULLTEXT_END---')) {
          fullText = aiResponse.split('---FULLTEXT_START---')[1].split('---FULLTEXT_END---')[0].trim();
        }
        if (!summary) summary = aiResponse;

        const cleanSummary = cleanVisionDescription(summary, docTargetLang);
        const cleanFull = cleanVisionDescription(fullText, docTargetLang);

        const docItem: SavedDocItem = {
          id: `audio_${Date.now()}`,
          title: lectureTitle,
          sourceType: 'audio',
          summary: cleanSummary || summary,
          fullText: cleanFull || fullText || recordedTranscript,
          targetLang: docTargetLang,
          createdAt: new Date().toISOString(),
        };

        setCurrentDoc(docItem);
        saveDocToHistory(docItem);
        setDocLoading(false);
        setDocStatusText('');

        const finalMsg = isAr
          ? `تم تلخيص المحاضرة الصوتية بنجاح! إليك الزبدة: ${cleanSummary || summary}`
          : `Audio lecture summary ready: ${cleanSummary || summary}`;
        onAnnounce?.(finalMsg);
        speak(finalMsg, isAr ? 'Arabic' : isFr ? 'French' : 'English');
      } catch (err) {
        console.error('Error processing audio recording:', err);
        setDocLoading(false);
        setDocStatusText('');
        toast.error(isAr ? 'حدث خطأ في معالجة الصوت.' : 'Error processing audio.');
      }
    };

    mediaRecorderRef.current.stop();
  };

  const handleAskDocQuestion = async () => {
    if (!docChatInput.trim() || !currentDoc || isDocChatAnswering) return;
    const question = docChatInput.trim();
    setDocChatInput('');
    setIsDocChatAnswering(true);

    const isAr = docTargetLang === 'ar';
    const isFr = docTargetLang === 'fr';

    setDocChatMessages((prev) => [...prev, { role: 'user', content: question }]);

    try {
      const prompt = `أنت معلم وأكاديمي متميز يشرح لطالب كفيف حول هذه المحاضرة/المستند:
عنوان المحاضرة: "${currentDoc.title}"
ملخص المحاضرة:
${currentDoc.summary}
تفاصيل المحتوى:
${currentDoc.fullText || ''}

سؤال الطالب: "${question}"

أجب على سؤال الطالب بشكل مباشر وواضح وودود بلغة ${isAr ? 'عربية عامية مصرية سهلة ومريحة للنطق الصوتي' : isFr ? 'française' : 'English'} وبدون أي نجوم ماركداون.`;

      const answer = await generateAdaptiveResponse(
        prompt,
        { ...profile, language: isAr ? 'Egyptian Ammiya' : isFr ? 'French' : 'English' },
        []
      );

      const cleanAnswer = cleanVisionDescription(answer, docTargetLang);
      setDocChatMessages((prev) => [...prev, { role: 'assistant', content: cleanAnswer }]);
      setIsDocChatAnswering(false);

      speak(cleanAnswer, isAr ? 'Arabic' : isFr ? 'French' : 'English', {
        onStart: () => setIsSpeakingDoc(true),
        onEnd: () => setIsSpeakingDoc(false),
        onError: () => setIsSpeakingDoc(false),
      });
    } catch {
      setIsDocChatAnswering(false);
      const errMsg = isAr ? 'حصل خطأ في الإجابة، جرب تسأل تاني.' : 'Error answering question, please try again.';
      setDocChatMessages((prev) => [...prev, { role: 'assistant', content: errMsg }]);
      speak(errMsg, isAr ? 'Arabic' : isFr ? 'French' : 'English');
    }
  };

  const toggleDictation = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      toast.error(
        companionLang === 'ar'
          ? 'المتصفح لا يدعم خاصية تحويل الصوت إلى كتابة التلقائية.'
          : 'Speech recognition is not supported in this browser.'
      );
      return;
    }

    if (isDictating) {
      if (speechRecRef.current) {
        try {
          speechRecRef.current.stop();
        } catch {
          /* ignore */
        }
        speechRecRef.current = null;
      }
      setIsDictating(false);
      toast.success(companionLang === 'ar' ? 'تم إنهاء الإملاء الصوتي' : 'Dictation stopped');
    } else {
      try {
        const rec = new SpeechRecognition();
        rec.continuous = true;
        rec.interimResults = true;
        rec.lang = docTargetLang === 'ar' ? 'ar-EG' : docTargetLang === 'fr' ? 'fr-FR' : 'en-US';

        rec.onresult = (event: any) => {
          let text = '';
          for (let i = 0; i < event.results.length; i++) {
            text += event.results[i][0].transcript + ' ';
          }
          setDictationText(text.trim());
        };

        rec.onerror = () => setIsDictating(false);
        rec.onend = () => setIsDictating(false);

        rec.start();
        speechRecRef.current = rec;
        setIsDictating(true);
        toast.info(companionLang === 'ar' ? 'تحدث الآن، صوتك يتحول لكتابة مباشرة...' : 'Listening... Speak now');
      } catch (err) {
        console.error('Dictation error:', err);
        setIsDictating(false);
      }
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-2 sm:p-4"
          onClick={onClose}
        >
          <motion.div
            role="dialog"
            aria-modal="true"
            aria-labelledby="doc-studio-title"
            initial={{ y: 30, opacity: 0, scale: 0.98 }}
            animate={{ y: 0, opacity: 1, scale: 1 }}
            exit={{ y: 30, opacity: 0, scale: 0.98 }}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-4xl bg-slate-900 rounded-3xl border border-slate-700/80 shadow-2xl text-white max-h-[92vh] flex flex-col overflow-hidden"
            dir={companionLang === 'ar' ? 'rtl' : 'ltr'}
          >
            {/* Header */}
            <div className="p-4 sm:p-5 border-b border-slate-800 flex items-center justify-between gap-3 flex-wrap bg-slate-950/70">
              <div className="flex items-center gap-2.5">
                <div className="w-10 h-10 rounded-2xl bg-indigo-600/30 border border-indigo-500/50 flex items-center justify-center text-indigo-400">
                  <FileText className="w-5 h-5" />
                </div>
                <div>
                  <h3 id="doc-studio-title" className="font-black text-base sm:text-lg text-white">
                    {companionLang === 'ar'
                      ? 'استوديو المستندات وتلخيص المحاضرات و PDF'
                      : companionLang === 'fr'
                      ? 'Studio Documents, Cours & PDF'
                      : 'Document, Lecture & PDF Studio'}
                  </h3>
                  <p className="text-xs text-slate-400">
                    {companionLang === 'ar'
                      ? 'قراءة PDF • استخراج الزبدة والمفيد • تحويل لـ Word • تسجيل صوتي • ترجمة'
                      : 'Read PDF • Summarize Lectures • Export to Word • Audio Recording • Translate'}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                {/* Target Translation Language Selector */}
                <div className="flex items-center bg-slate-900 border border-slate-700 p-1 rounded-xl text-xs font-bold">
                  <Languages className="w-3.5 h-3.5 text-indigo-400 mr-1.5 ml-1" />
                  <button
                    type="button"
                    onClick={() => setDocTargetLang('ar')}
                    className={`px-2 py-1 rounded-lg transition-all ${
                      docTargetLang === 'ar' ? 'bg-emerald-600 text-white' : 'text-slate-400 hover:text-white'
                    }`}
                    title="ترجمة وتلخيص بالعربية"
                  >
                    🇪🇬 عربي
                  </button>
                  <button
                    type="button"
                    onClick={() => setDocTargetLang('en')}
                    className={`px-2 py-1 rounded-lg transition-all ${
                      docTargetLang === 'en' ? 'bg-primary text-white' : 'text-slate-400 hover:text-white'
                    }`}
                    title="Translate to English"
                  >
                    🇬🇧 EN
                  </button>
                  <button
                    type="button"
                    onClick={() => setDocTargetLang('fr')}
                    className={`px-2 py-1 rounded-lg transition-all ${
                      docTargetLang === 'fr' ? 'bg-blue-600 text-white' : 'text-slate-400 hover:text-white'
                    }`}
                    title="Traduire en Français"
                  >
                    🇫🇷 FR
                  </button>
                </div>

                <button
                  onClick={() => {
                    cancelSpeech();
                    onClose();
                  }}
                  aria-label="Close"
                  className="p-2 rounded-xl hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Navigation Tabs */}
            <div className="flex border-b border-slate-800 px-4 gap-1 sm:gap-2 overflow-x-auto bg-slate-950/40">
              <button
                type="button"
                onClick={() => setDocStudioTab('pdf')}
                className={`py-3 px-3 sm:px-4 text-xs sm:text-sm font-bold flex items-center gap-2 border-b-2 transition-all whitespace-nowrap ${
                  docStudioTab === 'pdf'
                    ? 'border-indigo-500 text-indigo-400'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <FileUp className="w-4 h-4" />
                <span>{companionLang === 'ar' ? 'قارئ PDF والمستندات' : 'PDF & Doc Reader'}</span>
              </button>

              <button
                type="button"
                onClick={() => setDocStudioTab('audio-rec')}
                className={`py-3 px-3 sm:px-4 text-xs sm:text-sm font-bold flex items-center gap-2 border-b-2 transition-all whitespace-nowrap ${
                  docStudioTab === 'audio-rec'
                    ? 'border-red-500 text-red-400'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Mic className="w-4 h-4" />
                <span>{companionLang === 'ar' ? 'تسجيل وتلخيص المحاضرة' : 'Record & Summarize Lecture'}</span>
                {isRecordingAudio && <span className="w-2 h-2 rounded-full bg-red-500 animate-ping" />}
              </button>

              <button
                type="button"
                onClick={() => setDocStudioTab('speech-to-text')}
                className={`py-3 px-3 sm:px-4 text-xs sm:text-sm font-bold flex items-center gap-2 border-b-2 transition-all whitespace-nowrap ${
                  docStudioTab === 'speech-to-text'
                    ? 'border-emerald-500 text-emerald-400'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <Volume2 className="w-4 h-4" />
                <span>{companionLang === 'ar' ? 'صوت ↔ كتابة (Speech ↔ Text)' : 'Speech ↔ Text'}</span>
              </button>

              <button
                type="button"
                onClick={() => setDocStudioTab('history')}
                className={`py-3 px-3 sm:px-4 text-xs sm:text-sm font-bold flex items-center gap-2 border-b-2 transition-all whitespace-nowrap ${
                  docStudioTab === 'history'
                    ? 'border-amber-500 text-amber-400'
                    : 'border-transparent text-slate-400 hover:text-slate-200'
                }`}
              >
                <History className="w-4 h-4" />
                <span>{companionLang === 'ar' ? 'سجل المحفوظات' : 'Doc History'}</span>
                <span className="px-1.5 py-0.5 rounded-full bg-slate-800 text-[10px] text-slate-300">
                  {docHistory.length}
                </span>
              </button>
            </div>

            {/* Main Tab Content */}
            <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-5">
              {/* TAB 1: PDF & DOCUMENT READER */}
              {docStudioTab === 'pdf' && (
                <div className="space-y-5">
                  {/* Upload Card */}
                  <div className="border-2 border-dashed border-indigo-500/40 hover:border-indigo-400 rounded-3xl p-6 sm:p-8 bg-slate-950/40 text-center transition-all">
                    <input
                      type="file"
                      id="vision-doc-file-upload-modal"
                      accept=".pdf,image/*,.docx,.txt"
                      className="hidden"
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (file) processDocumentFile(file);
                        e.target.value = '';
                      }}
                    />
                    <label
                      htmlFor="vision-doc-file-upload-modal"
                      className="cursor-pointer flex flex-col items-center justify-center space-y-3"
                    >
                      <div className="w-16 h-16 rounded-3xl bg-indigo-600/20 border border-indigo-500/40 flex items-center justify-center text-indigo-400 shadow-xl group-hover:scale-105 transition-transform">
                        <FileUp className="w-8 h-8" />
                      </div>
                      <div className="space-y-1">
                        <p className="font-bold text-base sm:text-lg text-white">
                          {companionLang === 'ar'
                            ? 'اضغط هنا لرفع ملف PDF أو صورة مستند أو ورقة محاضرة'
                            : 'Click here to upload a PDF, document image, or lecture slide'}
                        </p>
                        <p className="text-xs text-slate-400">
                          {companionLang === 'ar'
                            ? 'يدعم ملفات PDF، الكتب، السلايدات، الصور والروشتات (مع استخراج الزبدة وترجمتها صوتياً)'
                            : 'Supports PDF, slides, lecture notes, textbook pages, and document photos'}
                        </p>
                      </div>
                      <span className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg active:scale-95 transition-all">
                        {companionLang === 'ar' ? 'اختر ملف من جهازك' : 'Choose Document File'}
                      </span>
                    </label>
                  </div>

                  {/* Loading State */}
                  {docLoading && (
                    <div className="p-6 rounded-2xl bg-indigo-950/40 border border-indigo-500/40 text-center space-y-3">
                      <Loader2 className="w-8 h-8 text-indigo-400 animate-spin mx-auto" />
                      <p className="font-bold text-sm sm:text-base text-indigo-200">
                        {docStatusText || (companionLang === 'ar' ? 'جاري فحص وتلخيص المستند بالذكاء الاصطناعي...' : 'Processing document with AI...')}
                      </p>
                    </div>
                  )}

                  {/* Document Display Result */}
                  {currentDoc && !docLoading && (
                    <div className="space-y-4 rounded-3xl bg-slate-950/70 border border-slate-800 p-4 sm:p-6 shadow-xl">
                      {/* Title & Action Bar */}
                      <div className="flex items-center justify-between gap-3 border-b border-slate-800 pb-4 flex-wrap">
                        <div className="space-y-1">
                          <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 rounded-lg bg-indigo-600/30 text-indigo-300 font-mono text-[10px] uppercase font-bold">
                              {currentDoc.sourceType}
                            </span>
                            <h4 className="font-black text-base sm:text-lg text-white">
                              {currentDoc.title}
                            </h4>
                          </div>
                          <span className="text-[11px] text-slate-400">
                            {new Date(currentDoc.createdAt).toLocaleString(companionLang === 'ar' ? 'ar-EG' : 'en-US')}
                          </span>
                        </div>

                        <div className="flex items-center gap-2 flex-wrap">
                          {/* Summary vs Full Text Toggle */}
                          <div className="flex p-1 bg-slate-900 rounded-xl border border-slate-800 text-xs font-bold">
                            <button
                              type="button"
                              onClick={() => setDocViewMode('summary')}
                              className={`px-2.5 py-1.5 rounded-lg flex items-center gap-1.5 transition-all ${
                                docViewMode === 'summary' ? 'bg-amber-500 text-black' : 'text-slate-400 hover:text-white'
                              }`}
                            >
                              <GraduationCap className="w-3.5 h-3.5" />
                              <span>{companionLang === 'ar' ? 'المفيد وخلاصة المحاضرة' : 'Summary'}</span>
                            </button>
                            <button
                              type="button"
                              onClick={() => setDocViewMode('full')}
                              className={`px-2.5 py-1.5 rounded-lg flex items-center gap-1.5 transition-all ${
                                docViewMode === 'full' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
                              }`}
                            >
                              <BookOpen className="w-3.5 h-3.5" />
                              <span>{companionLang === 'ar' ? 'النص المقروء كاملاً' : 'Full Text'}</span>
                            </button>
                          </div>

                          {/* Listen Aloud Button */}
                          <button
                            type="button"
                            onClick={() => {
                              const textToRead = docViewMode === 'summary' ? currentDoc.summary : currentDoc.fullText || currentDoc.summary;
                              if (isSpeakingDoc) {
                                cancelSpeech();
                                setIsSpeakingDoc(false);
                              } else {
                                cancelSpeech();
                                const lang = currentDoc.targetLang === 'ar' ? 'Arabic' : currentDoc.targetLang === 'fr' ? 'French' : 'English';
                                speak(textToRead, lang as any, {
                                  onStart: () => setIsSpeakingDoc(true),
                                  onEnd: () => setIsSpeakingDoc(false),
                                  onError: () => setIsSpeakingDoc(false),
                                });
                              }
                            }}
                            className={`px-3 py-2 rounded-xl font-bold text-xs flex items-center gap-1.5 shadow-lg active:scale-95 transition-all ${
                              isSpeakingDoc
                                ? 'bg-red-500 text-white animate-pulse'
                                : 'bg-emerald-600 hover:bg-emerald-500 text-white'
                            }`}
                          >
                            {isSpeakingDoc ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}
                            <span>{isSpeakingDoc ? (companionLang === 'ar' ? 'وقف الصوت' : 'Stop') : (companionLang === 'ar' ? 'استمع صوتياً' : 'Listen')}</span>
                          </button>

                          {/* Download as Word Button */}
                          <button
                            type="button"
                            onClick={() => {
                              exportToWordDocument(
                                currentDoc.title,
                                currentDoc.summary,
                                currentDoc.fullText,
                                currentDoc.targetLang
                              );
                              toast.success(companionLang === 'ar' ? 'تم تنزيل مستند Word بنجاح 📄' : 'Word document downloaded 📄');
                            }}
                            className="px-3 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs flex items-center gap-1.5 shadow-lg active:scale-95 transition-all"
                            title="تنزيل كملف Word صالح للفتح والتعديل"
                          >
                            <Download className="w-4 h-4" />
                            <span>{companionLang === 'ar' ? 'تحميل Word (.doc)' : 'Export Word'}</span>
                          </button>
                        </div>
                      </div>

                      {/* Content Viewer Box */}
                      <div className="p-4 sm:p-5 rounded-2xl bg-slate-900 border border-slate-800 max-h-72 overflow-y-auto leading-relaxed text-sm sm:text-base text-slate-100 font-medium">
                        {docViewMode === 'summary' ? (
                          <div className="space-y-2">
                            <span className="text-xs font-bold text-amber-400 block mb-1">
                              {companionLang === 'ar' ? '📌 الزبدة وخلاصة المحاضرة:' : '📌 Key Takeaways & Summary:'}
                            </span>
                            <p className="whitespace-pre-wrap">{currentDoc.summary}</p>
                          </div>
                        ) : (
                          <div className="space-y-2">
                            <span className="text-xs font-bold text-indigo-400 block mb-1">
                              {companionLang === 'ar' ? '📝 تفاصيل النص المستخرج كاملاً:' : '📝 Full Extracted Content:'}
                            </span>
                            <p className="whitespace-pre-wrap font-mono text-xs sm:text-sm">
                              {currentDoc.fullText || currentDoc.summary}
                            </p>
                          </div>
                        )}
                      </div>

                      {/* Interactive Q&A Mid-reading Section */}
                      <div className="space-y-3 pt-3 border-t border-slate-800">
                        <div className="flex items-center gap-2 text-xs font-bold text-slate-300">
                          <MessageSquare className="w-4 h-4 text-indigo-400" />
                          <span>
                            {companionLang === 'ar'
                              ? 'اسأل المعلم الذكي عن أي نقطة في هذه المحاضرة / المستند:'
                              : 'Ask the AI tutor any question about this document / lecture:'}
                          </span>
                        </div>

                        {/* Chat Messages */}
                        <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
                          {docChatMessages.map((msg, idx) => (
                            <div
                              key={idx}
                              className={`p-3 rounded-2xl text-xs sm:text-sm leading-relaxed ${
                                msg.role === 'user'
                                  ? 'bg-indigo-600/30 border border-indigo-500/40 text-indigo-100 mr-auto max-w-[85%]'
                                  : 'bg-slate-900 border border-slate-800 text-slate-200 ml-auto max-w-[85%]'
                              }`}
                            >
                              <span className="font-bold text-[10px] text-slate-400 block mb-0.5">
                                {msg.role === 'user'
                                  ? (companionLang === 'ar' ? 'أنت' : 'You')
                                  : (companionLang === 'ar' ? 'المعلم الذكي' : 'Cognify Tutor')}
                              </span>
                              <p>{msg.content}</p>
                            </div>
                          ))}
                        </div>

                        {/* Chat Input */}
                        <div className="flex gap-2">
                          <input
                            type="text"
                            value={docChatInput}
                            onChange={(e) => setDocChatInput(e.target.value)}
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') handleAskDocQuestion();
                            }}
                            placeholder={
                              companionLang === 'ar'
                                ? 'مثلاً: ما هي أهم معادلة في المحاضرة؟ أو اشرح لي النقطة الثانية...'
                                : 'Ask anything about this document...'
                            }
                            className="flex-1 px-4 py-2.5 rounded-xl border border-slate-700 bg-slate-950 text-white placeholder-slate-500 text-xs sm:text-sm outline-none focus:ring-2 focus:ring-indigo-500"
                          />
                          <button
                            type="button"
                            onClick={handleAskDocQuestion}
                            disabled={!docChatInput.trim() || isDocChatAnswering}
                            className="px-4 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl text-xs sm:text-sm flex items-center gap-1.5 shadow-lg active:scale-95 disabled:opacity-40 transition-all"
                          >
                            {isDocChatAnswering ? (
                              <Loader2 className="w-4 h-4 animate-spin" />
                            ) : (
                              <Send className="w-4 h-4" />
                            )}
                            <span>{companionLang === 'ar' ? 'إرسال' : 'Send'}</span>
                          </button>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* TAB 2: LIVE AUDIO LECTURE RECORDING */}
              {docStudioTab === 'audio-rec' && (
                <div className="space-y-6 text-center py-4">
                  <div className="max-w-md mx-auto space-y-2">
                    <h4 className="font-black text-lg text-white">
                      {companionLang === 'ar'
                        ? 'تسجيل وتلخيص المحاضرة الصوتية الحية'
                        : 'Live Audio Lecture Recording & Summarizer'}
                    </h4>
                    <p className="text-xs text-slate-400 leading-relaxed">
                      {companionLang === 'ar'
                        ? 'شغّل التسجيل أثناء وجودك في قاعة المحاضرات، وسيقوم الذكاء بتفريغ كلام الدكتور واستخراج الزبدة والمفيد وتجهيز ملف Word فوراً.'
                        : 'Record live in the lecture hall. Cognify AI will transcribe the professor, extract core takeaways, and prepare a Word doc immediately.'}
                    </p>
                  </div>

                  {/* Big Accessible Record Button */}
                  <div className="flex flex-col items-center justify-center py-4 space-y-4">
                    <button
                      type="button"
                      onClick={() => {
                        if (isRecordingAudio) {
                          stopAudioLectureRecording();
                        } else {
                          startAudioLectureRecording();
                        }
                      }}
                      disabled={docLoading}
                      aria-pressed={isRecordingAudio}
                      aria-label={isRecordingAudio ? 'Stop Recording' : 'Start Recording'}
                      className={`w-28 h-28 rounded-full flex flex-col items-center justify-center gap-1.5 shadow-2xl active:scale-95 transition-all ${
                        isRecordingAudio
                          ? 'bg-red-600 text-white ring-8 ring-red-500/30 animate-pulse'
                          : 'bg-gradient-to-tr from-red-600 to-rose-500 hover:from-red-500 hover:to-rose-400 text-white ring-8 ring-red-950/40'
                      }`}
                    >
                      {isRecordingAudio ? <MicOff className="w-10 h-10" /> : <Mic className="w-10 h-10" />}
                      <span className="text-[11px] font-black">
                        {isRecordingAudio
                          ? (companionLang === 'ar' ? 'إنهاء وتلخيص' : 'Stop & Summarize')
                          : (companionLang === 'ar' ? 'ابدأ التسجيل' : 'Record')}
                      </span>
                    </button>

                    {isRecordingAudio && (
                      <div className="space-y-1">
                        <span className="font-mono text-2xl font-black text-red-400 tracking-wider">
                          {Math.floor(audioRecordDuration / 60)}:
                          {(audioRecordDuration % 60).toString().padStart(2, '0')}
                        </span>
                        <p className="text-xs text-slate-400 animate-pulse">
                          {companionLang === 'ar' ? 'جاري الاستماع للمحاضرة وتفريغ الكلام مباشرة...' : 'Listening and transcribing live lecture...'}
                        </p>
                      </div>
                    )}
                  </div>

                  {/* Live Transcript Preview */}
                  {liveSpeechTranscript && (
                    <div className="max-w-xl mx-auto p-4 rounded-2xl bg-slate-950/60 border border-slate-800 text-start space-y-1.5">
                      <span className="text-[11px] font-bold text-red-400 block">
                        {companionLang === 'ar' ? 'تفريغ فوري مباشر أثناء التحدث:' : 'Live Transcript Stream:'}
                      </span>
                      <p className="text-xs text-slate-300 font-mono leading-relaxed line-clamp-4">
                        {liveSpeechTranscript}
                      </p>
                    </div>
                  )}
                </div>
              )}

              {/* TAB 3: SPEECH ↔ TEXT STUDIO */}
              {docStudioTab === 'speech-to-text' && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Panel A: Speech to Text (Voice Dictation) */}
                  <div className="p-4 sm:p-5 rounded-3xl bg-slate-950/70 border border-slate-800 space-y-3 flex flex-col">
                    <div className="flex items-center justify-between">
                      <h4 className="font-black text-sm text-emerald-400 flex items-center gap-1.5">
                        <Mic className="w-4 h-4" />
                        <span>{companionLang === 'ar' ? 'تحدث ليكتب لك (إملاء صوتي)' : 'Speech to Text (Dictation)'}</span>
                      </h4>
                      <button
                        type="button"
                        onClick={toggleDictation}
                        className={`px-3 py-1.5 rounded-xl font-bold text-xs flex items-center gap-1.5 transition-all shadow ${
                          isDictating
                            ? 'bg-red-600 text-white animate-pulse'
                            : 'bg-emerald-600 hover:bg-emerald-500 text-white'
                        }`}
                      >
                        {isDictating ? <MicOff className="w-3.5 h-3.5" /> : <Mic className="w-3.5 h-3.5" />}
                        <span>{isDictating ? (companionLang === 'ar' ? 'إيقاف' : 'Stop') : (companionLang === 'ar' ? 'تحدث الآن' : 'Dictate')}</span>
                      </button>
                    </div>

                    <textarea
                      rows={7}
                      value={dictationText}
                      onChange={(e) => setDictationText(e.target.value)}
                      placeholder={
                        companionLang === 'ar'
                          ? 'اضغط على "تحدث الآن" وابدأ الكلام، وسيتم كتابة كل ما تقوله بدقة هنا...'
                          : 'Click "Dictate" and start speaking. Your speech will appear here...'
                      }
                      className="w-full flex-1 p-3 rounded-2xl bg-slate-900 border border-slate-700 text-white placeholder-slate-500 text-xs sm:text-sm outline-none focus:ring-2 focus:ring-emerald-500 leading-relaxed resize-none"
                    />

                    <div className="flex gap-2 flex-wrap">
                      <button
                        type="button"
                        onClick={() => {
                          if (!dictationText.trim()) return;
                          navigator.clipboard.writeText(dictationText);
                          toast.success(companionLang === 'ar' ? 'تم نسخ النص المكتوب 📋' : 'Copied to clipboard 📋');
                        }}
                        disabled={!dictationText.trim()}
                        className="px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs disabled:opacity-40"
                      >
                        {companionLang === 'ar' ? 'نسخ النص' : 'Copy'}
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          if (!dictationText.trim()) return;
                          exportToWordDocument(
                            companionLang === 'ar' ? 'إملاء صوتي' : 'Dictation Note',
                            dictationText,
                            undefined,
                            docTargetLang
                          );
                          toast.success(companionLang === 'ar' ? 'تم حفظ ملف Word 📄' : 'Word file saved 📄');
                        }}
                        disabled={!dictationText.trim()}
                        className="px-3 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs flex items-center gap-1 disabled:opacity-40"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>{companionLang === 'ar' ? 'تصدير Word' : 'Export Word'}</span>
                      </button>
                    </div>
                  </div>

                  {/* Panel B: Text to Speech (Text Reader) */}
                  <div className="p-4 sm:p-5 rounded-3xl bg-slate-950/70 border border-slate-800 space-y-3 flex flex-col">
                    <div className="flex items-center justify-between">
                      <h4 className="font-black text-sm text-blue-400 flex items-center gap-1.5">
                        <Volume2 className="w-4 h-4" />
                        <span>{companionLang === 'ar' ? 'اكتب ليقرأ لك بصوت واضح' : 'Text to Speech Reader'}</span>
                      </h4>
                    </div>

                    <textarea
                      rows={7}
                      value={textToReadAloud}
                      onChange={(e) => setTextToReadAloud(e.target.value)}
                      placeholder={
                        companionLang === 'ar'
                          ? 'الصق أو اكتب أي نص هنا لسماعه فوراً بصوت طبيعي واضح...'
                          : 'Paste or type any text here to hear it read aloud...'
                      }
                      className="w-full flex-1 p-3 rounded-2xl bg-slate-900 border border-slate-700 text-white placeholder-slate-500 text-xs sm:text-sm outline-none focus:ring-2 focus:ring-blue-500 leading-relaxed resize-none"
                    />

                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={() => {
                          if (!textToReadAloud.trim()) return;
                          cancelSpeech();
                          const lang = docTargetLang === 'ar' ? 'Arabic' : docTargetLang === 'fr' ? 'French' : 'English';
                          speak(textToReadAloud, lang as any, {
                            onStart: () => setIsSpeakingDoc(true),
                            onEnd: () => setIsSpeakingDoc(false),
                            onError: () => setIsSpeakingDoc(false),
                          });
                        }}
                        disabled={!textToReadAloud.trim()}
                        className="flex-1 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs flex items-center justify-center gap-1.5 shadow-lg disabled:opacity-40 active:scale-95 transition-all"
                      >
                        <Volume2 className="w-4 h-4" />
                        <span>{companionLang === 'ar' ? 'اقرأ بصوت عالي' : 'Read Aloud'}</span>
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          cancelSpeech();
                          setIsSpeakingDoc(false);
                        }}
                        className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold text-xs"
                      >
                        {companionLang === 'ar' ? 'إيقاف' : 'Stop'}
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 4: SAVED DOCUMENTS ARCHIVE */}
              {docStudioTab === 'history' && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between text-xs text-slate-400 pb-2 border-b border-slate-800">
                    <span>{companionLang === 'ar' ? 'المستندات والمحاضرات التي تم تلخيصها سابقاً' : 'Previously Summarized Documents'}</span>
                    <span className="font-mono text-indigo-400 font-bold">{docHistory.length} items</span>
                  </div>

                  {docHistory.length === 0 ? (
                    <div className="text-center py-12 text-slate-500 space-y-2">
                      <FileText className="w-10 h-10 mx-auto opacity-40 text-slate-400" />
                      <p className="text-sm font-bold text-slate-400">
                        {companionLang === 'ar'
                          ? 'لا توجد مستندات محفوظة بعد.'
                          : 'No saved documents in your archive yet.'}
                      </p>
                      <p className="text-xs text-slate-500">
                        {companionLang === 'ar'
                          ? 'ارفع أي ملف PDF أو سجّل محاضرة وسيتم حفظ ملخصها هنا تلقائياً.'
                          : 'Upload a PDF or record a lecture to have its summary saved here automatically.'}
                      </p>
                    </div>
                  ) : (
                    docHistory.map((item) => (
                      <div
                        key={item.id}
                        className="p-4 rounded-2xl bg-slate-950/60 border border-slate-800 flex items-center justify-between gap-3 hover:border-slate-700 transition-all flex-wrap sm:flex-nowrap"
                      >
                        <div className="space-y-1 flex-1 min-w-0">
                          <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 rounded-md bg-indigo-600/30 text-indigo-300 font-mono text-[10px] uppercase font-bold">
                              {item.sourceType}
                            </span>
                            <h5 className="font-bold text-sm text-white truncate">{item.title}</h5>
                          </div>
                          <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">
                            {item.summary}
                          </p>
                          <span className="text-[10px] text-slate-500 block">
                            {new Date(item.createdAt).toLocaleDateString(companionLang === 'ar' ? 'ar-EG' : 'en-US')}
                          </span>
                        </div>

                        <div className="flex items-center gap-1.5 shrink-0">
                          <button
                            type="button"
                            onClick={() => {
                              setCurrentDoc(item);
                              setDocStudioTab('pdf');
                            }}
                            className="px-3 py-1.5 rounded-xl bg-indigo-600/30 hover:bg-indigo-600/50 text-indigo-300 font-bold text-xs"
                          >
                            {companionLang === 'ar' ? 'فتح' : 'Open'}
                          </button>
                          <button
                            type="button"
                            onClick={() => {
                              exportToWordDocument(item.title, item.summary, item.fullText, item.targetLang);
                              toast.success(companionLang === 'ar' ? 'تم تنزيل Word 📄' : 'Word downloaded 📄');
                            }}
                            className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-blue-400"
                            title="تحميل كملف Word"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                          <button
                            type="button"
                            onClick={() => deleteDocFromHistory(item.id)}
                            className="p-2 rounded-xl bg-slate-800 hover:bg-red-500/20 text-slate-400 hover:text-red-400"
                            title="حذف"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
